name: Error
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  error:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run error
