name: Re-run workflow if job failed

on:
  workflow_run:
    workflows:
      - Error
    types:
      - completed

jobs:
  retry:
    name: Re-run workflow if job failed
    if: github.event.workflow_run.conclusion == 'failure' || github.event.workflow_run.conclusion == 'timed_out'
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Retry
        uses: gesposito/action-workflow-retry@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          firebase_project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
          firebase_api_key: ${{ secrets.FIREBASE_API_KEY }}
          owner: ${{ github.event.workflow_run.repository.owner.login }}
          repo: ${{ github.event.workflow_run.repository.name }}
          run_id: ${{ github.event.workflow_run.id }}
